package com.rainmonth.notebook.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.rainmonth.notebook.entity.CostEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "Cost".
*/
public class CostEntityDao extends AbstractDao<CostEntity, Long> {

    public static final String TABLENAME = "Cost";

    /**
     * Properties of entity CostEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CostType = new Property(1, Integer.class, "costType", false, "COST_TYPE");
        public final static Property CostNum = new Property(2, Integer.class, "costNum", false, "COST_NUM");
        public final static Property CostTime = new Property(3, Long.class, "costTime", false, "COST_TIME");
    }


    public CostEntityDao(DaoConfig config) {
        super(config);
    }
    
    public CostEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"Cost\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"COST_TYPE\" INTEGER," + // 1: costType
                "\"COST_NUM\" INTEGER," + // 2: costNum
                "\"COST_TIME\" INTEGER);"); // 3: costTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"Cost\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CostEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer costType = entity.getCostType();
        if (costType != null) {
            stmt.bindLong(2, costType);
        }
 
        Integer costNum = entity.getCostNum();
        if (costNum != null) {
            stmt.bindLong(3, costNum);
        }
 
        Long costTime = entity.getCostTime();
        if (costTime != null) {
            stmt.bindLong(4, costTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CostEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer costType = entity.getCostType();
        if (costType != null) {
            stmt.bindLong(2, costType);
        }
 
        Integer costNum = entity.getCostNum();
        if (costNum != null) {
            stmt.bindLong(3, costNum);
        }
 
        Long costTime = entity.getCostTime();
        if (costTime != null) {
            stmt.bindLong(4, costTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CostEntity readEntity(Cursor cursor, int offset) {
        CostEntity entity = new CostEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // costType
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // costNum
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // costTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CostEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCostType(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setCostNum(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setCostTime(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CostEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CostEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CostEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
